### ISSUE TITLE
Any guidelines to integrate this with angular 2 project generated from ng-cli?

### ISSUE THREAD

**Issue by vinayakpatil** [sneas/component-library#4]

**Comment by sneas** [comment]
I don't think Component Library is good candidate as a styleguide for an Angular 2 app. Since Angular 2 provides SPA approach and barely could be used with non-angular environment, I think it's better to try Angular-specific component library like https://github.com/swimlane/ngx-ui .

**Comment by vinayakpatil** [comment]
@sneas cool, thank you for a quick reply!
